FROM node:20-alpine

# Instala OpenSSL
RUN apk add --no-cache openssl

WORKDIR /usr/src/app

# COPIA CRÍTICA: Copia tudo de uma vez, incluindo package.json e o código fonte
COPY . .

# 1. Instala as dependências (agora o package.json existe)
RUN npm install 
RUN npx prisma generate

# 2. Garante permissão de execução
RUN chmod -R +x .

# 3. Compila e Inicia
RUN npm run build 
CMD ["npm", "start"]