FROM node:18-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache openssl
COPY backend/package*.json ./ 
COPY prisma/ ./prisma/ 
RUN npm install 
RUN npx prisma generate
COPY backend/ .
RUN chmod -R +x .
RUN npm run build 
CMD ["npm", "start"]